site_name: TechBook
nav:
  - Home: index.md
  - Azure:
    - Inicio: azure/index.md
    - AZ-104:
        - M04 - Gobernanza:
          - Azure Policy: azure/az-104/m04/azure_policy.md
        - M09 - Virtual Machines:
          - Disk Encryption: azure/az-104/m09/disk_encryption.md
        - M14 - Redes Virtuales:
          - Private Endpoint: azure/az-104/m14/private_endpoint.md
          - Private Link: azure/az-104/m14/private_link.md
          - Endpoint de Servicio: azure/az-104/m14/service_endpoint.md
        - M16 - Recuperación:
          - Site Recovery: azure/az-104/m16/site_recovery.md
theme:
  name: material
  locale: es
  features:
    - navigation.tabs
    - navigation.instant